---
- name: Install fontconfig
  yum:
    name: fontconfig
    state: present

- name: Add grafana repository
  yum_repository:
    name: grafana
    description: "repository for grafana"
    baseurl: https://packages.grafana.com/oss/rpm
    enabled: 1
    gpgcheck: 1
    gpgkey: https://packages.grafana.com/gpg.key
    sslverify: 1
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    file: grafana

- name: Install grafana
  yum:
    name: grafana
    enablerepo: grafana

- name: Ensure grafana-server is started
  service:
    name: grafana-server
    enabled: yes
    state: started

- name: install zabbix-plugin to grafana
  shell: grafana-cli plugins install alexanderzobnin-zabbix-app
  ignore_errors: yes

- name: copy grafana.ini
  template:
    src: "roles/grafana/files/grafana.ini.j2"
    dest: "/etc/grafana/grafana.ini"
    mode: 0644
  notify: restart grafana
