#########################################################
# Grafana/Zabbix on CentOS7
#########################################################

---
- hosts: all
  become: true
  roles:
    - common

- hosts: web
  become: true
  roles:
    - php
    - ssl
    - h2o
    - zabbix
    - mysql
    - grafana
