---
- name: Install the remi and ius repo from remote repo
  yum:
    name:
      - "http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
      - "https://centos7.iuscommunity.org/ius-release.rpm"

- name: Install PHP modules
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: latest
    enablerepo: "{{ php_version }}"
  loop: "{{ php_modules }}"

- name: Set ownership
  file:
    path: "/var/lib/php"
    state: directory
    recurse: yes
    owner: "{{ remote_web_user }}"
    group: "{{ remote_web_user }}"

- name: Ensure php-fpm is started
  service:
    name: php-fpm
    state: started
    enabled: true

- name: Copy php.ini
  copy:
    src: "roles/php/files/php.ini"
    dest: "/etc/php.ini"
    backup: yes
  notify: restart php

- name: Copy www.conf
  template:
    src: "roles/php/files/www.conf.j2"
    dest: "/etc/php-fpm.d/www.conf"
  notify: restart php
